### ISSUE TITLE
Error: Cannot find module 'pokemon-go-api'

### ISSUE THREAD

**Issue by kfernandes29** [carldanley/node-pokemon-go-api#1]
After installing the npm package and attempting to run the node server, I get:

`module.js:442
    throw err;
    ^

Error: Cannot find module 'pokemon-go-api'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kfernandes29/Documents/Windows Azure/pocketgochat/api/login.js:3:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
MacBook-Pro:pocketgochat kfernandes29$ `

**Comment by carldanley** [comment]
How silly of me; fixed by https://github.com/carldanley/node-pokemon-go-api/commit/56f0acd9c1875e0410f2a1142bb096350c79af82.
