### ISSUE TITLE
If user is not with a team, app crashes

### ISSUE THREAD

**Issue by aidenwallis** [carldanley/node-pokemon-go-api#14]
As you can see, my test account is not with a team, and this is what I get:-

> error Error: Missing at least one required field for Message .ProfileResponse.Profile: team
    at Error (native)
    at ProtoBuf.Reflect.MessagePrototype.decode (/Users/aiden/DEV/pokechampion/node_modules/protobufjs/dist/protobuf.js:3255:35)
    at ProtoBuf.Reflect.ElementPrototype.decode (/Users/aiden/DEV/pokechampion/node_modules/protobufjs/dist/protobuf.js:2185:46)
    at ProtoBuf.Reflect.FieldPrototype.decode (/Users/aiden/DEV/pokechampion/node_modules/protobufjs/dist/protobuf.js:3727:33)
    at ProtoBuf.Reflect.MessagePrototype.decode (/Users/aiden/DEV/pokechampion/node_modules/protobufjs/dist/protobuf.js:3238:45)
    at Function.Message.decode (/Users/aiden/DEV/pokechampion/node_modules/protobufjs/dist/protobuf.js:2933:37)
    at /Users/aiden/DEV/pokechampion/node_modules/pokemon-go-api/src/requests/get-profile.js:16:44
    at tryCatcher (/Users/aiden/DEV/pokechampion/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/aiden/DEV/pokechampion/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/Users/aiden/DEV/pokechampion/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/Users/aiden/DEV/pokechampion/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/Users/aiden/DEV/pokechampion/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/Users/aiden/DEV/pokechampion/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/aiden/DEV/pokechampion/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/Users/aiden/DEV/pokechampion/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:570:20)

**Comment by aidenwallis** [comment]
So here's what I did to fix it so it works for all players, in your profile protos, just set avatar and team from required to optional, hope that helps anyone, the app works great now! :)
