### ISSUE TITLE
getMapDataByCoordinates:  Illegal value for Message.Field .RequestEnvelope.latitude of type double: object (required)

### ISSUE THREAD

**Issue by christocracy** [carldanley/node-pokemon-go-api#3]
Running `examples/get-map-data-by-coordinates.js`:

```bash
error Error: Illegal value for Message.Field .RequestEnvelope.latitude of type double: object (required)
    at Error (native)
    at fail (/Users/chris/Documents/workspace/tmp/pokemon/node_modules/pokemon-go-api/node_modules/protobufjs/dist/protobuf.js:3440:23)
    at ProtoBuf.Reflect.FieldPrototype.verifyValue (/Users/chris/Documents/workspace/tmp/pokemon/node_modules/pokemon-go-api/node_modules/protobufjs/dist/protobuf.js:3444:21)
    at MessagePrototype.set (/Users/chris/Documents/workspace/tmp/pokemon/node_modules/pokemon-go-api/node_modules/protobufjs/dist/protobuf.js:2475:59)
    at MessagePrototype.set (/Users/chris/Documents/workspace/tmp/pokemon/node_modules/pokemon-go-api/node_modules/protobufjs/dist/protobuf.js:2466:38)
    at Message (/Users/chris/Documents/workspace/tmp/pokemon/node_modules/pokemon-go-api/node_modules/protobufjs/dist/protobuf.js:2395:34)
    at Object.sendRaw (/Users/chris/Documents/workspace/tmp/pokemon/node_modules/pokemon-go-api/src/utils/request/rpc.js:20:25)
    at module.exports (/Users/chris/Documents/workspace/tmp/pokemon/node_modules/pokemon-go-api/src/requests/get-player-endpoint.js:18:6)
    at fn.getPlayerEndpoint (/Users/chris/Documents/workspace/tmp/pokemon/node_modules/pokemon-go-api/index.js:120:66)
    at tryCatcher (/Users/chris/Documents/workspace/tmp/pokemon/node_modules/pokemon-go-api/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/chris/Documents/workspace/tmp/pokemon/node_modules/pokemon-go-api/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/Users/chris/Documents/workspace/tmp/pokemon/node_modules/pokemon-go-api/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/Users/chris/Documents/workspace/tmp/pokemon/node_modules/pokemon-go-api/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/Users/chris/Documents/workspace/tmp/pokemon/node_modules/pokemon-go-api/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/Users/chris/Documents/workspace/tmp/pokemon/node_modules/pokemon-go-api/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/chris/Documents/workspace/tmp/pokemon/node_modules/pokemon-go-api/node_modules/bluebird/js/release/async.js:148:10)
```

**Comment by carldanley** [comment]
Can you submit the exact file you used (with the sample info you used)? Make sure you redact your username and password before posting it.

**Comment by christocracy** [comment]
```Javascript
// internal dependencies
const api = require('pokemon-go-api');
const _ = require('lodash');

// constants/variables
const username = '<username>;
const password = '<password>';
const provider = 'google';

// main code

api.login(username, password, provider)
  .then(api.getPlayerEndpoint)
  .then(_.partial(api.mapData.getByCoordinates, 40.707914, -74.005845))
  .then(function(data) {
    console.log('success', data);
  })
  .catch(function(error) {
    console.log('error', error.stack);
  });

```

**Comment by renedx** [comment]
With me these examples didn't work either using google auth. Besides lodash not being included in one, it errors on the same for coodinates but with inventory it throws this;
```
error Error: Missing at least one required field for Message .ProfileResponse.Profile: team
    at Error (native)
    at ProtoBuf.Reflect.MessagePrototype.decode (/Users/rene/node_modules/protobufjs/dist/protobuf.js:3255:35)
    at ProtoBuf.Reflect.ElementPrototype.decode (/Users/rene/node_modules/protobufjs/dist/protobuf.js:2185:46)
    at ProtoBuf.Reflect.FieldPrototype.decode (/Users/rene/node_modules/protobufjs/dist/protobuf.js:3727:33)
    at ProtoBuf.Reflect.MessagePrototype.decode (/Users/rene/node_modules/protobufjs/dist/protobuf.js:3238:45)
    at Function.Message.decode (/Users/rene/node_modules/protobufjs/dist/protobuf.js:2933:37)
    at /Users/rene/node_modules/pokemon-go-api/src/requests/get-profile.js:16:44
    at tryCatcher (/Users/rene/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/rene/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/Users/rene/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/Users/rene/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/Users/rene/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/Users/rene/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/rene/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/rene/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
```

**Comment by bennesp** [comment]
Same for me, with both the examples. Has anyone discovered what was wrong?

**Comment by weiry6922** [comment]
For the profile/inventory example, I changed team in the profile proto to optional and it works. I think it's when it tries to get the profiles team but it isn't part of a team yet.

**Comment by 1475963** [comment]
I've the same issue, I tried to set team as optional in the profile proto but I get the same error even with an account that has a team.

**Comment by LiquidSnake2ITA** [comment]
Same for me, I'got the same error with both example files (coordinates and location name).

**Comment by bbraybrook** [comment]
the getPlayerEndpoint call is sending the cached latitude and longitude, which don't exist yet.

as a workaround, add this prior to calling login:
api.cache.location.latitude = 40.707914;
api.cache.location.longitude = -74.005845;

**Comment by 1475963** [comment]
Thanks for the trick
