### ISSUE TITLE
Cannot login with google

### ISSUE THREAD

**Issue by bennesp** [carldanley/node-pokemon-go-api#6]
Unhandled rejection Error: 403 error from server
    at IncomingMessage.<anonymous> (/path_of_project/node_modules/pokemon-go-api/node_modules/gpsoauthnode/oauth.js:61:23)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:903:12)
    at doNTCallback2 (node.js:439:9)
    at process._tickDomainCallback (node.js:394:17)

**Comment by bennesp** [comment]
Solved, sorry.

Using username@gmail.com throw an error.
Using only username (without @gmail.com) works.
