### ISSUE TITLE
Inventory example returns Null for all fields

### ISSUE THREAD

**Issue by Harrisandwich** [carldanley/node-pokemon-go-api#8]
I'm not sure if this is my problem or an actual API issue, but when I do the inventory example the JSON returned has 'null' in every field. It's logging in properly because my email address got sent an email saying the api logged in.

**Comment by stoffern** [comment]
@Harrisandwich https://github.com/stoffern/pokemongo-api :)

**Comment by carldanley** [comment]
ooh @stoffern nice - will check it out later today after work.

**Comment by Harrisandwich** [comment]
@stoffern Are there better examples for how to use this api? I think I'm missing a few packages to allow for the "import" and "async" keywords in the example in the repo. Perhaps a list of dependancies in order to use it?

**Comment by stoffern** [comment]
you go:
`npm i -S pokemongo-api`
all dependencies will be installed automaticly, altho you need Visual Studio installed to compile a module.

we dont provide bot examples..

From example file or read docs.. it should be quite easy, if not then dont use JS :smile: :
```js
const Poke = new PokeAPI()
//login
const api = await Poke.login(username, password, provider)
// just update the profile...
let player = await Poke.GetPlayer()

// get map objects..
while( true ){
  let cells = await Poke.GetMapObjects()
  for(let cell of cells) {
    // catchable pokemons from here?
    if (cell.catchable_pokemons.length > 0){
      cell.catchable_pokemons.map(pokemon => {
        pokemon.encounterAndCatch()
      })
    }

    // wild pokemons
    if (cell.wild_pokemons.length > 0){
      // we have wild pokemons, you cannot catch these..
    }

    // forts
    if (cell.forts.length > 0){
      // forts..
      for (let fort of cell.forts){
        if (fort.isCheckpoint)
          fort.search()
      }
    }
  }
  
  //just walk a little (1 - 15 meters..)
  await Poke.player.walkAround()

  await new Promise(resolve => setTimeout(resolve, 3000))
}
```

**Comment by Harrisandwich** [comment]
@stoffern hmmmm I'm using that example exactly as is. Perhaps I'm missing something.

**Comment by stoffern** [comment]
Do you get an error?

**Comment by Harrisandwich** [comment]
@stoffern  this is my error: 

import env from 'node-env-file'
^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3

**Comment by stoffern** [comment]
well import is a ES6 syntax so if you dont use babel then you have to require the file.
var Poke = require('pokemongo-api')

did you clone the repo or install from npm?

**Comment by Harrisandwich** [comment]
@stoffern Ill move this over to the other repo

**Comment by Harrisandwich** [comment]
@carldanley this issue still stands as is. In order to use @stoffern 's api it looked like it would need es6 or es7 to operate. I would like what I'm planning to be compatible with most browsers. It's not necessarily for personal use.
