### ISSUE TITLE
Cannot login with pokemon-club

### ISSUE THREAD

**Issue by kzka90** [carldanley/node-pokemon-go-api#9]
error Error: Error parsing body
    at /path/node_modules/pokemon-go-api/src/login.js:89:34
    at tryCatcher (/path/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler

Printed data.body, and it's an empty string.

**Comment by ashlux** [comment]
+1

**Comment by stigbosmans** [comment]
+1
